### PR TITLE
added try-catch and fix error

### PR DESCRIPTION
**Pull request by DFSko**
resolves https://github.com/happy-travel/ueda/issues/189

### CODE REVIEW

**Review by mingazhev — COMMENTED** [review]
Try-catches are not our way. Need to add appropriate validation without throwing exceptions.
Exceptions exist in AgentInAgencyId as a fallback, to ensure its proper work. Normally code should not reach them

**Comment by kirillta** [comment]
So, where's the try-catch?

**Comment by DFSko** [comment]
> So, where's the try-catch?

Removed

**Comment by DFSko** [comment]
> Try-catches are not our way. Need to add appropriate validation without throwing exceptions. Exceptions exist in AgentInAgencyId as a fallback, to ensure its proper work. Normally code should not reach them

Fixed

**Review by kirillta — APPROVED** [review]

**Pull request merged**
