### PR TITLE
updating markup storage on event instead of timer

### PR DESCRIPTION
**Pull request by DFSko**

### CODE REVIEW

**Review by kirillta — COMMENTED** [review]
Why do you need a vender-locked multiplexer for this?

**Comment by DFSko** [comment]
> Why do you need a vender-locked multiplexer for this?

Hided implementation in separate service

**Review by kirillta — COMMENTED** [review]
I think, you should use remove instead of update. That's more resilient and common cache interaction.

**Comment by kirillta** [comment]
Untitled

**Pull request closed without merging**
